# Generated by Django 5.0.6 on 2024-07-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateTimeField(
                default=1,
                help_text="Введите дату производства продукта",
                verbose_name="Дата произодства",
            ),
            preserve_default=False,
        ),
    ]
