# Generated by Django 5.0.6 on 2024-07-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_manufactured_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="manufactured_at",
        ),
    ]
