# Generated by Django 5.0.6 on 2024-08-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Введите номер версии продукта",
                        verbose_name="Номер версии",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="Введите название версии продукта",
                        max_length=200,
                        verbose_name="Название версии",
                    ),
                ),
                (
                    "current_version_indicator",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите, является ли текущая версия",
                        verbose_name="Текущая версия",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Введите продукт",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_versions",
                        to="product.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия продукта",
                "verbose_name_plural": "Версии продуктов",
            },
        ),
    ]
