# Generated by Django 4.2.2 on 2024-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    (
                        "can_cancel_publication_product",
                        "Can cancel publication product",
                    ),
                    (
                        "can_change_description_product",
                        "Can change description product",
                    ),
                    ("can_change_category_product", "Can change category product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.BooleanField(
                default=False,
                help_text="Опубликовать продукт",
                verbose_name="Опубликовано",
            ),
        ),
    ]
